### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by blackslate** [lexogram/TEFLRef#1]
### Reference windows
- [x] set links in other windows
- [x] activate appropriate tab in each window, according to flags
- [ ] update display in other windows when expression is modified
- [x] bring reference windows to front when updated
- [x] deal with closed reference windows
- [x] close reference windows when extension is disabled or the host tab closes

### TEFL Reference Panel layout
- [x] add automatic regex changes for
```
    -   try tries tried  trying
    -   tie ties  tied   tying
    -   tow tows  towed  towiing
    -   rot rots  rotted rotting
    -   owe owes  owed   owing
```
- [x] allow user to add expressions to link to
- [x] add button to remove all spans and recreate them
- [x] send updated expressions to client page
- [x] show how many occurrences there are of an expression
- [x] disable up and down buttons if there is only one occurrence
- [x] add button to delete an expression
- [ ] disable refresh windows button if no changes have been made
- [ ] add button to set flags according to what tabs are selected
    - [x] add about:blank tab to each window, for "none" 
- [ ] add Save button which sets simple HTML + expression declaration and saves page

### Editor panel
- [x] show matches for input in regexField
- [ ] automatically show matches for current regex when it is opened
- [ ] provide input field for custom tag
- [ ] insert tag into HTML for different meanings of words
- [ ] fix CSS
- [ ] fix button icon

### Output
- [x] order expressions by length, so most complex are applied first
    - [ ] restore this order when exporting array
- [x] goExpression should be ordered by text position

### Visual feedback
- [x] show coloured pageAction icon if extension is active
- [x] click on word to jump to its entry
